### ISSUE TITLE
Step 5 fund.js : invalid opcode: opcode 0xfe not defined

### ISSUE THREAD

**Issue by netproject0** [PatrickAlphaC/weather-nft#2]
Hi,
I've ran step 1 to 4 with Mumbai Network with information found in  https://blog.chain.link/matic-defi-price-feeds/
    * Link token : 0x70d1F773A9f81C852087B77F6Ae6d3032B02D2AB
    * Oracle : 0x1cf7D49BE7e0c6AC30dEd720623490B64F572E17 
    * Job ID : d8fcf41ee8984d3b8b0eae7b74eca7dd
    * fee: '1000000000000000000'
    * fundAmount: '40000000000000000'

Right now i'm blocked in step 5 fund.js =>  "invalid opcode: opcode 0xfe not defined"
that's all.
Note : For step 4 (mint.js), log told me "View your NFTs on Opensea! https://opensea.io/assets/matic/0x728D09Ac31d192FeB41eb1bf9B921cC225635Aa1/0" => I've a 404 error.

Could you help ?
Best.

**Comment by PatrickAlphaC** [comment]
I haven't had much success recently with the mumbai testnet. Please use another testnet like kovan or rinkeby.

**Comment by danielbanfield** [comment]
In case it's of help to anyone, you need to use the mumbai testnet opensea url, so for netproject0 you'll find his NFT at
https://testnets.opensea.io/assets/mumbai/0x728D09Ac31d192FeB41eb1bf9B921cC225635Aa1/0

~~I got the fund.js migration to work by using the oracle and job id of netproject0, but a LINK token contract: 0x326C977E6efc84E512bB9C30f76E30c160eD06FB 
see https://docs.chain.link/docs/link-token-contracts/#mumbai-testnet~~

~~Now I'm stuck with "Error: execution reverted: Must use LINK token" on the 6_get_weather.js migration. There appears to be some kind of mismatch of the LINK token contract but I can't find it.~~

It turns out the oracle quoted by netproject0 was also out of date.

https://docs.polygon.technology/docs/develop/oracles/chainlink/#addresses

So in helper-scripts.js:

```
80001: {
        name: 'mumbai',
        linkToken: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB',
        oracle: '0xb33D8A4e62236eA91F3a8fD7ab15A95B9B7eEc7D',
        weatherJobId: 'd8fcf41ee8984d3b8b0eae7b74eca7dd',
        passwordJobId: '',
        fee: '10000000000000000',
        fundAmount: '40000000000000000',
    }
```

has given me a successful run on mumbai.
